gatekeeper/urls.py
#from registration.backends.default.views import RegistrationView
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import object_tools

from django.contrib import admin
from adminplus.sites import AdminSitePlus

admin.site.index_template = 'admin/gatekeeper/change_form.html'
admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = [
    # Examples:
#    url(r'^$', 'gatekeeperapp.views.home', name='home'),
    url(r'^', include('gatekeeperapp.urls')),
    #url(r'^nh5/', include('nh5.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    #url(r'^jet/', include('jet.urls', 'jet')),
    #url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_export/', include("admin_export.urls", namespace="admin_export")),
    url(r'^object-tools/', include(object_tools.tools.urls)) 
    #url(r'^accounts2/', include('users.urls')),
    #url(r'^accounts/', include('registration.backends.default.urls')),
#    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
#   url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    #url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    ##url(r'^accounts/password/reset/$', 'accounts.views.password_reset', name='password_reset'),
    #url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    #url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
    #url(r'^accounts/password/reset/$', include('registration.backends.default.urls')),
    

]



if settings.DEBUG:
        import debug_toolbar
        urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

admin.site.site_header = 'Gatekeeper'

gateuser/urls.py
__author__ = 'rt'
from django.conf.urls import patterns, url
from nh5 import views, models
from registration.backends.default.views import RegistrationView
from nh5.forms import CustomUserCreationForm


urlpatterns = patterns('',
        url(r'^$', views.index, name ='index'),
	      
       )

userprofile_2/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.contrib import admin
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail

        
class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)
        
        



class Employee(AbstractBaseUser, PermissionsMixin):
    """
    A fully featured User model with admin-compliant permissions that uses
    a full-length email field as the username.

    Email and password are required. Other fields are optional.
    """
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    name = models.CharField(_('name'), max_length=30, blank=True)
    phone = models.CharField(max_length = 20, blank = False, null = False)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.email)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = self.name
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])
        
        

templates/registration_old/activate.html
{% extends 'base.html' %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Activation {% endblock %}

{% block content_block %}

<p>{% trans "Account activation failed" %}</p>

{% endblock %}

templates/registration_old/login.html
{% extends 'base.html' %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Login {% endblock %}

         {% block content_block %}


<div class="row">
<div class="module form-module">
  
  <div class="form">
<form class = "form-horizontal loginform" role="form" method="post" action=".">
                                           {% csrf_token %}
						{{form.errors}}
    <h2>Login to your account</h2>
    <form>
      <input required="required" id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
      <input required="required" id="id_password" name="password" type="password" placeholder="Password">
    <input type="submit" value="submit" class="submit-login">
    </form>
  </div>
  
  <div class="cta"><a href="/accounts/password/reset/">Forgot your password?</a></div>
  <div class="cta"><a href="/accounts/register/">Register</a></div>
</div>
</div>

<style>
.form-module {
    position: relative;
    background: #ffffff;
    max-width: 322px;
    width: 100%;
    border-top: 5px solid #005689;
    box-shadow: 0 0 3px rgba(0, 0, 0, 0.1);
    margin: 0 auto;
    padding-bottom: 10px;
}
.form-module .form:nth-child(2) {
    display: block;
}
.form-module .form {
    
    padding: 40px;
}
.form-module h2 {
    margin: 0 0 20px;
    color: #005689;
    font-size: 18px;
    font-weight: 400;
    line-height: 1;
}
.form-module input {
    outline: none;
    display: block;
    width: 100%;
    border: 1px solid #d9d9d9;
    margin: 0 0 20px;
    padding: 10px 15px;
    box-sizing: border-box;
    font-wieght: 400;
    -webkit-transition: 0.3s ease;
    transition: 0.3s ease;
}
form input.submit-login {
    cursor: pointer;
    background: #005689;
    width: 100%;
    border: 0;
    padding: 10px 15px;
    color: #ffffff;
    -webkit-transition: 0.3s ease;
    transition: 0.3s ease;
}
.form-module .cta {
    background: #f2f2f2;
    width: 100%;
    padding: 15px 40px;
    box-sizing: border-box;
    color: #005689;
    font-size: 12px;
    text-align: center;
}

</style>
{% endblock %}

templates/registration_old/login1.html
{% extends 'base-dash2.html' %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Login {% endblock %}

         {% block content_block %}

       <div class="container">
                        <div class="col-md-12 column logincol">
                            
                            
                                   <legend>Login</legend>
                                      <form class = "form-horizontal loginform" role="form" method="post" action=".">
                                           {% csrf_token %} 
                                        <div class="form-group">
  <label class="col-md-4 control-label" for="id_username">Username</label>  
  <div class="col-md-4">
  <input required="required" id="id_username" maxlength="30" name="username" type="text" class="form-control input-md">

  </div>
</div>
                                       <div class="form-group">
  <label class="col-md-4 control-label" for="id_password1">Password</label>
  <div class="col-md-4">
    <input required="required" id="id_password" name="password" type="password" class="form-control input-md">

  </div>
</div>
                                        <div class="submit">
                                        <button type="submit" class="btn btn-default loginbutton"><b>Submit</b></button>
                                       
                                        </div>
                                      </form>

                                     <p class="loginhelp">{% trans "Forgot password" %}? <a href="/accounts/password/reset/">{% trans "Reset it" %}</a>!</p>
                                        <p>{% trans "Not member" %}? <a href="/accounts/register/">{% trans "Register" %}</a>!</p>
                                              


         </div>
</div>      

{% endblock %}

templates/registration_old/logout.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Smart Vizag Logout {% endblock %}

   {% block content_block %}

<h2>  Logged Out </h2>


{% endblock %}


templates/registration_old/nh5login.html
{% extends "nh5/base.html" %}
    {% load static %}


       
       
{% block content%}

      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
                                        <legend> Sign In</legend>
                            <form class = "form-horizontal loginform" role="form" method="post" action=".">
                                           {% csrf_token %} 
                                        <div class="form-group">
  <label class="col-md-4 control-label" for="id_username">Username</label>  
  <div class="col-md-4">
  <input required="required" id="id_username" maxlength="30" name="username" type="text" class="form-control input-md">

  </div>
</div>
                                       <div class="form-group">
  <label class="col-md-4 control-label" for="id_password1">Password</label>
  <div class="col-md-4">
    <input required="required" id="id_password" name="password" type="password" class="form-control input-md">

  </div>
</div>
                                        <div class="submit loginsubmit">
                                        <button type="submit" class="btn btn-default loginbutton"><b>Submit</b></button>
                                       
                                             <p class = "registerpara">
                                        <a href="/accounts/nh5register" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            <u> Sign Up Here </u> &nbsp;&nbsp;&nbsp;
                                        </a>
     <a href="/accounts/password/reset/" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            <u>Forgot Password </u>
                                        </a> </p>
                                        
                                        </div>
                                  
                                        
                                        
                                      </form>
        
        
        
        
              </div>
      </div>
    </div>
      
    


{% endblock %}

templates/registration_old/nh5logout.html


{% extends "nh5/base.html" %}
    {% load static %}


       
       
{% block content%}

      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
                                      
                            <h2>  Logged Out </h2>
        
        
        
              </div>
      </div>
    </div>
      
    


{% endblock %}

templates/registration_old/nh5register.html
{% extends "nh5/base.html" %}
    {% load static %}


       
       
{% block content%}

      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
      
                        <form class="form-horizontal" role="form" method="post" action=".">
                               {% csrf_token %}         
<fieldset>

<!-- Form Name -->
<legend> Please fill in this form to register</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Name</label>  
  <div class="col-md-4">
  <input id="id_email" name="username" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Name</label>  
  <div class="col-md-4">
  <input id="id_name" name="username" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Name</label>  
  <div class="col-md-4">
  <input id="id_company_name" name="username" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>


<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Mobile</label>  
  <div class="col-md-4">
  <input id="id_phone" name="phone" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Mobile</label>  
  <div class="col-md-4">
  <input id="id_address" name="phone" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>


<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Password</label>  
  <div class="col-md-4">
  <input id="id_password1" name="password1" type="password" placeholder="" class="form-control input-md">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Type Password Again</label>  
  <div class="col-md-4">
  <input id="id_password2" name="password2" type="password" placeholder="" class="form-control input-md">
    
  </div>
</div>

<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="selectbasic">Category Type</label>
  <div class="col-md-4">
    <select id="id_type" name="selectbasic" class="form-control">
    <option value="" selected="selected">---------</option>
<option value="Architect">Architect</option>
<option value="Interior Designer">Interior Designer</option>
<option value="Project Management Consultant">Project Management Consultant</option>
<option value="Contractor">Contractor</option>
<option value="Material Supplier">Material Supplier</option>
<option value="Builder">Builder</option>
    </select>
  </div>
</div>

<!-- Button -->
  <div class="submit loginsubmit">
                                        <button type="submit" class="btn btn-default loginbutton"><b>Submit</b></button>
                                       
                                          
                                        </div>

</fieldset>
</form>

        
        
        
        
              </div>
      </div>
    </div>
      
    


{% endblock %}

templates/registration_old/password_reset_confirm.html
{% extends 'base.html' %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Password Reset Confirm {% endblock %}

   {% block content_block %}



      <div class="container logincont" style="margin-top:100px;">
          
          
            <div class="row">
		<div class="col-md-12">
      
      
{% if validlink %}

<form method="post" action=".">
  {% csrf_token %} 
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>

{% else %}

<p>{% trans "Password reset failed" %}</p>

{% endif %}



        
              </div>
      </div>
    </div>
      
    
    
    
{% endblock %}

templates/registration_old/password_reset_done.html
{% extends "base.html" %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Password Reset Done {% endblock %}

    {% block content_block %}
   
   
      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
      
      
<p>{% trans "Email with password reset instructions has been sent." %}</p>


      </div>
      </div>
    </div>
    
    
{% endblock %}

templates/registration_old/password_reset_email.html
{% load i18n %}
{% blocktrans %}Reset password at {{ site_name }}{% endblocktrans %}:
{% block reset_link %}


{{ protocol }}://{{ domain }}{% url 'auth_password_reset_confirm' uid token %}
{% endblock %}

templates/registration_old/password_reset_form.html
{% extends "base.html" %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag - Password Reset Form {% endblock %}

   {% block content_block %}
   
   
      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
      
      
<form method="post" action="/accounts/password/reset/">
  {% csrf_token %} 
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>

     
              </div>
      </div>
    </div>
      
    
    
    

{% endblock %}

templates/registration_old/registration_closed.html
{% extends 'base.html' %}
 {% load i18n %}


{% load static %}
{% block title %} Smart Vizag Registration Closed {% endblock %}

{% block content_block %}
	<p>{% trans "Registration is currently closed." %}</p>
{% endblock %}

templates/registration_old/registration_complete.html
{% extends "base.html" %}
 {% load i18n %}


{% load static %}
{% block title %} SmartVizag Registration {% endblock %}

  {% block content_block %}
   
   
      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
      
      
<p>{% trans "Thank you for registering with SmartVizag. Activation email sent." %}</p>

      </div>
      </div>
    </div>
    
    
{% endblock %}

templates/registration_old/registration_form1.html
{% extends "base.html" %}
    {% load static %}


       
       
{% block content_block %}

      <div class="container logincont">
          
          
            <div class="row">
		<div class="col-md-12">
      
                        <form class="form-horizontal" role="form" method="post" action="">
                               {% csrf_token %} 
				{{ form.errors }}        
<fieldset>

<!-- Form Name -->
<legend> Please fill in this form to register</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Email</label>  
  <div class="col-md-4">
  <input id="id_email" name="email" type="email" placeholder="" class="form-control input-md">
    
  </div>
</div>

<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Name</label>  
  <div class="col-md-4">
  <input id="id_name" name="name" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>



<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Phone</label>  
  <div class="col-md-4">
  <input id="id_phone" name="phone" type="text" placeholder="" class="form-control input-md">
    
  </div>
</div>


<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Password</label>  
  <div class="col-md-4">
  <input id="id_password1" name="password1" type="password" placeholder="" class="form-control input-md">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Type Password Again</label>  
  <div class="col-md-4">
  <input id="id_password2" name="password2" type="password" placeholder="" class="form-control input-md">
    
  </div>
</div>


<!-- Button -->
  <div class="submit loginsubmit">
                                        <button type="submit" class="btn btn-default loginbutton"><b>Submit</b></button>
                                       
                                          
                                        </div>

</fieldset>
</form>

        
        
        
        
              </div>
      </div>
    </div>
      
    


{% endblock %}